title: "Advent of Code 2020 解答ガイド"
summary: |-
  Advent of Codeは、毎年12月に1日から25日間、毎日問題が出題されるプログラミングパズルです。
  Rustで解答した個人記録をPythonで書き直してまとめ直しました。
  各日各partの問題の概要・解答例の他に、考え方についても簡単にですが書いています。
  日本語情報がまだ少なくハードルが高いと思われるかもしれませんが、本書をきっかけに挑戦してみる仲間が増えてくれると嬉しいです。
topics: ["adventofcode", "python"]
published: true
allow_override: true
price: 0
toc_depth: 0
chapters:
  - introduction
  - day01
  - day02
  - day03
  - day04
  - day05
  - day06
  - day07
  - day08
  - day09
  - day10
  - day11
  - day12
  - day13
  - day14
  - day15
  - day16
  - day17
  - day18
  - day19
  - day20
  - day21
  - day22
  - day23
  - day24
  - day25
